const FICTIONAL_STUDENTS = [
  {
    email: 'seed_phoenix42@mits.example',
    password: 'Password123!',
    anonymousName: 'BluePhoenix42',
    avatar: 'avatar_preset_1',
    department: 'Computer Science & Engineering',
    year: '3rd Year',
    bio: 'Building full-stack MERN apps & exploring AI agents. Always down for hackathons and coffee!',
    interests: ['Coding & Web Dev', 'AI & Machine Learning', 'Hackathons & Projects', 'Coffee & Conversations'],
    lookingFor: ['Study Partner', 'Hackathon Teammate', 'Project Collaborator'],
  },
  {
    email: 'seed_moon18@mits.example',
    password: 'Password123!',
    anonymousName: 'SilentMoon18',
    avatar: 'avatar_preset_6',
    department: 'Data Science & Artificial Intelligence',
    year: '2nd Year',
    bio: 'Data enthusiast, night owl, and anime binge-watcher. Looking for study partners and gaming mates.',
    interests: ['AI & Machine Learning', 'Anime & Manga', 'PC & Console Gaming', 'Books & Literature'],
    lookingFor: ['Study Partner', 'Gaming Partner', 'Campus Friend'],
  },
  {
    email: 'seed_coder27@mits.example',
    password: 'Password123!',
    anonymousName: 'MysteryCoder27',
    avatar: 'avatar_preset_3',
    department: 'Information Technology',
    year: '4th Year',
    bio: 'Final year IT student prepping for campus placements and open-source contributions.',
    interests: ['Coding & Web Dev', 'Hackathons & Projects', 'Chess & Strategy', 'UI/UX & Design'],
    lookingFor: ['Project Collaborator', 'Study Partner'],
  },
  {
    email: 'seed_panda99@mits.example',
    password: 'Password123!',
    anonymousName: 'QuantumPanda99',
    avatar: 'avatar_preset_2',
    department: 'Electronics & Communication',
    year: '2nd Year',
    bio: 'Robotics hobbyist, music creator, and casual Valorant player.',
    interests: ['Music & Jamming', 'Esports & Mobile Gaming', 'PC & Console Gaming', 'Cricket'],
    lookingFor: ['Gaming Partner', 'Campus Friend', 'Coffee & Chat'],
  },
  {
    email: 'seed_panther07@mits.example',
    password: 'Password123!',
    anonymousName: 'NeonPanther07',
    avatar: 'avatar_preset_5',
    department: 'Mechanical Engineering',
    year: '3rd Year',
    bio: 'CAD design, Formula Student racing, and fitness enthusiast.',
    interests: ['Fitness & Gym', 'Football', 'Travel & Exploring', 'Movies & Series'],
    lookingFor: ['Campus Friend', 'Dating & Relationship'],
  },
  {
    email: 'seed_falcon14@mits.example',
    password: 'Password123!',
    anonymousName: 'CosmicFalcon14',
    avatar: 'avatar_preset_4',
    department: 'Civil Engineering',
    year: '1st Year',
    bio: 'Freshman exploring campus clubs, photography, and weekend football matches.',
    interests: ['Photography & Video', 'Football', 'Travel & Exploring', 'Movies & Series'],
    lookingFor: ['Campus Friend', 'Coffee & Chat'],
  },
  {
    email: 'seed_tiger88@mits.example',
    password: 'Password123!',
    anonymousName: 'HyperTiger88',
    avatar: 'avatar_preset_7',
    department: 'Business Administration (MBA)',
    year: 'Postgraduate',
    bio: 'Startup enthusiast, market analyst, and coffee lover.',
    interests: ['Startups & Tech', 'Coffee & Conversations', 'Chess & Strategy', 'Books & Literature'],
    lookingFor: ['Hackathon Teammate', 'Project Collaborator', 'Coffee & Chat'],
  },
  {
    email: 'seed_fox33@mits.example',
    password: 'Password123!',
    anonymousName: 'AstralFox33',
    avatar: 'avatar_preset_8',
    department: 'Biotechnology',
    year: '3rd Year',
    bio: 'Bioinformatics student fascinated by genetic algorithms and classical guitar.',
    interests: ['AI & Machine Learning', 'Music & Jamming', 'Books & Literature', 'Fitness & Gym'],
    lookingFor: ['Study Partner', 'Campus Friend'],
  },
  {
    email: 'seed_owl55@mits.example',
    password: 'Password123!',
    anonymousName: 'MysticOwl55',
    avatar: 'avatar_preset_9',
    department: 'Humanities & Basic Sciences',
    year: '1st Year',
    bio: 'Poetry writer, indie music listener, and campus library regular.',
    interests: ['Books & Literature', 'Music & Jamming', 'Coffee & Conversations', 'Anime & Manga'],
    lookingFor: ['Campus Friend', 'Dating & Relationship'],
  },
  {
    email: 'seed_voyager12@mits.example',
    password: 'Password123!',
    anonymousName: 'CyberVoyager12',
    avatar: 'avatar_preset_1',
    department: 'Computer Science & Engineering',
    year: '2nd Year',
    bio: 'Competitive programmer (Codeforces Specialist) and open-source enthusiast.',
    interests: ['Coding & Web Dev', 'Hackathons & Projects', 'Chess & Strategy'],
    lookingFor: ['Study Partner', 'Hackathon Teammate'],
  },
  {
    email: 'seed_starlight91@mits.example',
    password: 'Password123!',
    anonymousName: 'StarlightCoder91',
    avatar: 'avatar_preset_3',
    department: 'Data Science & Artificial Intelligence',
    year: '3rd Year',
    bio: 'Deep learning researcher interested in NLP and computer vision.',
    interests: ['AI & Machine Learning', 'Coding & Web Dev', 'Photography & Video'],
    lookingFor: ['Project Collaborator', 'Study Partner'],
  },
  {
    email: 'seed_shadow77@mits.example',
    password: 'Password123!',
    anonymousName: 'ShadowKnight77',
    avatar: 'avatar_preset_6',
    department: 'Electrical & Electronics',
    year: '4th Year',
    bio: 'Embedded systems tinkerer, IoT enthusiast, and rock music listener.',
    interests: ['Startups & Tech', 'Music & Jamming', 'Cricket'],
    lookingFor: ['Project Collaborator', 'Campus Friend'],
  },
  {
    email: 'seed_aurora23@mits.example',
    password: 'Password123!',
    anonymousName: 'RadiantAura23',
    avatar: 'avatar_preset_5',
    department: 'Information Technology',
    year: '1st Year',
    bio: 'UI/UX design lover creating Figma wireframes and mobile mockups.',
    interests: ['UI/UX & Design', 'Photography & Video', 'Anime & Manga'],
    lookingFor: ['Project Collaborator', 'Campus Friend'],
  },
  {
    email: 'seed_comet64@mits.example',
    password: 'Password123!',
    anonymousName: 'SolarComet64',
    avatar: 'avatar_preset_4',
    department: 'Mechanical Engineering',
    year: '2nd Year',
    bio: 'Badminton player, automotive enthusiast, and sci-fi film buff.',
    interests: ['Movies & Series', 'Travel & Exploring', 'Fitness & Gym'],
    lookingFor: ['Campus Friend', 'Gaming Partner'],
  },
  {
    email: 'seed_prism15@mits.example',
    password: 'Password123!',
    anonymousName: 'PrismNomad15',
    avatar: 'avatar_preset_2',
    department: 'Electronics & Communication',
    year: '3rd Year',
    bio: 'Wireless communications student and acoustic guitarist.',
    interests: ['Music & Jamming', 'Cricket', 'Coffee & Conversations'],
    lookingFor: ['Campus Friend', 'Dating & Relationship'],
  },
];

module.exports = { FICTIONAL_STUDENTS };
